s3:
  credentials:
    accessKey: ${AWS_ACCESS_KEY:dummy}
    secretKey: ${AWS_SECRET_KEY:dummy}
  region: ${S3_REGION:us-east-1}
  bucket: ${S3_BUCKET:dummy}

#logging:
#  level:
#    org:
#      springframework: DEBUG
